services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=Darksanpaio
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=root
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wendellmottasilva356@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "We.242007"
    ports:
      - "54321:80"
    depends_on:
      - postgres
